server:
  port: 8080  # Gateway runs on port 8080

spring:
  cloud:
    gateway:
      routes:
        - id: test_controller
          uri: http://localhost:8080
          predicates:
            - Path=/test
        - id: auth_service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: quiz_service
          uri: http://localhost:8082
          predicates:
            - Path=/quiz/**
      default-filters:
        - AddResponseHeader=X-Gateway, QuizAPI
