version: "3.9"

networks:
  quiznet:

volumes:
  mysql_data:

services:
  gateway:
    build: ../api-gateway
    container_name: gateway
    environment:
      CORS_ALLOWED_ORIGINS: 
      AUTH_URL: http://auth-service:8081
      QMS_URL:  http://qms-service:8082
      RTS_URL:  http://rts-service:8085
    ports:
      - "8080:8080"
    depends_on: [auth-service, qms-service, rts-service]
    networks: [quiznet]

  auth-service:
    build: ../auth-service
    container_name: auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/quiz_auth?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: 
      SPRING_DATASOURCE_PASSWORD: 
      JWT_SECRET: 
      GOOGLE_CLIENT_ID: 
      GOOGLE_CLIENT_SECRET: 
      GOOGLE_ALLOWED_REDIRECT_URIS: 
      SERVER_PORT: 8081
    depends_on: [mysql]
    networks: [quiznet]

  qms-service:
    build: ../qms-service
    container_name: qms-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/quiz_core?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: 
      SPRING_DATASOURCE_PASSWORD: 
      JWT_SECRET: 
      SERVER_PORT: 8082
    depends_on: [mysql]
    networks: [quiznet]

  rts-service:
    build: ../rts-service
    container_name: rts-service
    environment:
      SERVER_PORT: 8085
      REDIS_URL: redis://redis:6379
      JWT_SECRET: 
      CORS_ALLOWED_ORIGINS: 
    depends_on: [redis]
    networks: [quiznet]

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: live_quiz            
    volumes:
      - mysql_data:/var/lib/mysql
      - ../infra/db:/docker-entrypoint-initdb.d 
    ports:
      - "3306:3306" # dev only
    networks: [quiznet]

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379" # dev only
    networks: [quiznet]
